// Assembles src/levels/fixed.js from the exact shape constructors and the screenshot
// extraction in tools/out/levels.json. Run: node tools/build_fixed.mjs
import fs from 'node:fs';
import { ring, grid, rings } from '../src/levels/shapes.js';

const extracted = Object.fromEntries(
  JSON.parse(fs.readFileSync('tools/out/levels.json', 'utf8')).map((l) => [l.id, l]),
);

const SPEC = [
  [1, '2×2 Square', () => grid(2)],
  [2, '5-dot Ring', () => ring(5)],
  [3, '6-dot Ring', () => ring(6)],
  [4, '3×3 Square', () => grid(3)],
  [5, 'Two Shapes', () => extracted[5]],
  [6, '10-dot Ring', () => ring(10)],
  [7, 'Double Ring', () => extracted[7]],
  [8, 'Square with Triangle', () => extracted[8]],
  [9, '16-dot Ring', () => ring(16)],
  [10, '4×4 Square', () => grid(4)],
  [11, 'Two Polylines', () => extracted[11]],
  [12, 'Square in Square', () => extracted[12]],
  [13, 'Square in Star', () => extracted[13]],
  [14, '24-dot Ring', () => ring(24)],
  [15, '5×5 Square', () => grid(5)],
  [16, 'Double Ring II', () => extracted[16]],
  [17, '6×6 Square', () => grid(6)],
  [18, '3 Rings', () => rings(3)],
  [19, '4 Rings', () => rings(4)],
  [20, '5 Rings', () => rings(5)],
  [21, '6 Rings', () => rings(6)],
  [22, '7 Rings', () => rings(7)],
];

const levels = SPEC.map(([id, name, build]) => {
  const { slots, edges, width, height } = build();
  return { id, name, width, height, slots, edges };
});

fs.writeFileSync(
  'src/levels/fixed.js',
  '// GENERATED by tools/build_fixed.mjs — do not edit by hand.\n' +
    'export default ' + JSON.stringify(levels) + ';\n',
);
console.log(levels.map((l) => `${l.id} ${l.name}: ${l.slots.length} nodes, ${l.edges.length} edges`).join('\n'));
